# Generated by Django 5.1.4 on 2024-12-18 11:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_decision_updated_at_con_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='share_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
