# Generated by Django 5.1.4 on 2024-12-18 11:16

from django.db import migrations
from django.db import models
from uuid import uuid4

def gen_uuid(apps, schema_editor):
    Team = apps.get_model('main', 'Team')
    for team in Team.objects.all():
        team.share_id = uuid4()
        team.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_team_share_id'),
    ]

    operations = [
        # First, populate existing rows with UUIDs
        migrations.RunPython(gen_uuid),
        
        # Then, make the field unique and non-nullable
        migrations.AlterField(
            model_name='team',
            name='share_id',
            field=models.UUIDField(default=uuid4, editable=False, unique=True),
        ),
    ]
