#!/bin/bash

if ! which docker-compose >/dev/null; then
    echo -- Installing Docker -- 

    # https://www.fosstechnix.com/how-to-install-docker-on-ubuntu-24-04-lts/

    # Update the package list
    sudo apt-get update

    # Install packages to allow apt to use a repository over HTTPS
    sudo apt-get install -y \
        apt-transport-https \
        ca-certificates \
        curl \
        gnupg-agent \
        software-properties-common

    sudo install -m 0755 -d /etc/apt/keyrings

    sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc

    sudo chmod a+r /etc/apt/keyrings/docker.asc

    # Add the Docker repository to APT sources
    echo \
        "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
        $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
        sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

    # Update the package list again
    sudo apt-get update

    # Install the latest version of Docker CE
    sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
    
    # Add the current user to the Docker group
    sudo usermod -aG docker $USER

    # # Install Docker Compose
    # echo -- Installing Docker Compose -- 
    # sudo curl -L "https://github.com/docker/compose/releases/download/v2.15.1/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose

    # # Apply executable permissions to the binary
    # sudo chmod +x /usr/local/bin/docker-compose

    # Install git 
    sudo apt-get install -y git
fi